### ISSUE TITLE
add become: true

### ISSUE THREAD

**Issue by hmoffatt** [jeffwarnica/subXidUpdate#3]
Thanks for this role! It's very handy, since ansible seems reluctant to add something to the core.

I notice that you didn't set become: true in the role's own tasks. I use the following on the include_role task instead; perhaps you could add this to the example in the documentation?

```
  ansible.builtin.include_role:
    name: subXidUpdate
    apply:
      become: true
```
